name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gather release notes from CHANGELOG
        id: notes
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          awk -v tag="$TAG" '
            BEGIN { print "## " tag "\n" }
            $0 ~ "^## \\"?\[" tag "\]" { printing=1; next }
            printing && $0 ~ /^## / { printing=0 }
            printing { print }
          ' CHANGELOG.md > RELEASE_NOTES.md || true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
